apiVersion: v1
kind: Service
metadata:
  name: test-nodejs-1
  namespace: "test1"
  labels:
    app: test-nodejs-1
spec:
  ports:
  - name: http
    port: 31000
    targetPort: 3000
  selector:
    app: test-nodejs-express-server