apiVersion: v1
kind: Service
metadata:
  name: test-nodejs-1
  namespace: "test1"
  labels:
    app: test-nodejs-1
spec:
  # type: ClusterIP # default
  # type: LoadBalancer 
  type: NodePort
  ports:
  - name: http
    port: 3000 # 30000 - 32767 https://cloud.ibm.com/docs/containers?topic=containers-nodeport#nodeport_config
    nodePort: 31000
    # targetPort: 3000
  selector:
    app: test-nodejs-1